Repository conaticus/boolean, pull requests merged in 2022-05, with the labels that each got.

#120 General Cleanup + Implementing ESLint + Prettier
  .eslintignore
  .eslintrc.json
  .prettierignore
  .prettierrc.json
  package.json
  src/commands/quiz.ts
  src/database/index.ts
  src/index.ts
  src/structures/Bot.ts
  src/utils.ts
Labels: enhancement

#126 Improved the announce command to use Discord modals now that they're supported
  src/commands/announce.ts
Labels: bug, enhancement

#128 Enforce Linter Rules
  .github/workflows/CI.yaml
  src/commands/announce.ts
  src/commands/clear.ts
  src/commands/config.ts
  src/commands/deleteSuggestion.ts
  src/commands/deny.ts
  src/commands/ping.ts
  src/commands/quiz.ts
  src/commands/repeat.ts
  src/commands/roleme.ts
  src/commands/selfrole.ts
  src/commands/suggest.ts
  src/commands/user.ts
  src/commands/verbal.ts
  src/database/badges.ts
  src/database/index.ts
  src/database/selfroles.ts
  src/events/guildMemberRemove.ts
  src/events/guildMemberUpdate.ts
  src/events/messageCreate.ts
  src/events/messageDelete.ts
  src/events/messageUpdate.ts
  src/events/ready.ts
  src/files.ts
  src/index.ts
  src/structures/Bot.ts
  src/structures/BotCommand.ts
  src/structures/Logger.ts
  src/structures/index.ts
  src/utils.ts
Labels: proposal

#127 Allowed attachments in suggestions
  src/commands/suggest.ts
Labels: enhancement

#140 Fix Jest Config
  jest.config.js
  src/commands/ping.ts
Labels: enhancement
